### PR TITLE
Add server and publisher port configuration

### PR DESCRIPTION
**Pull request by Sarath18**
Related to issue #68. I have added support for changing server and publisher ports in Groot's UI. The result can be seen in the following image.

groot

### CODE REVIEW

**Comment by Sarath18** [comment]
@facontidavide did you get a chance to look into this?

**Comment by facontidavide** [comment]
not yet. I am very busy with other stuff, sorry

**Comment by facontidavide** [comment]
I am rewriting the publisher to be sure that the two ports are always consecutive numbers, being

     server_port = puhlisherport + 1

This means that you might make this assumption here and remove the LineEdit for Server port.

**Comment by Sarath18** [comment]
No problem. I'll make the necessary changes.

**Comment by facontidavide** [comment]
done

thanks for contributing

**Comment by Sarath18** [comment]
> server_port = puhlisherport + 1

@facontidavide May I ask why did you revert this change in the commit [1962fd23c](https://github.com/BehaviorTree/Groot/commit/1962fd23c376b012762a109ed1222dbcb13ce3f6) ?

**Pull request merged**
