### PR TITLE
Adapt to API changes in BehaviorTree

### PR DESCRIPTION
**Pull request by galou**
The change was introduced in 474f33b and was mentioned in #169 and #171 .

### CODE REVIEW

**Comment by galou** [comment]
Any comment?

**Comment by enfuri51** [comment]
When change the code ad you mentioned, the build will throw the error like this. Is the correction complete? @galou 
`
error: invalid initialization of reference of type ‘const std::set<std::__cxx11::basic_string<char> >&’ from expression of type ‘std::unordered_map<std::__cxx11::basic_string<char>, BT::NodeType>’
  199 |         BT::VerifyXML(xml_text, registered_nodes); // may throw`

**Comment by galou** [comment]
I wrote a fix that allows to compile again but Groot segfaults...

**Comment by galou** [comment]
I just realized that the fix actually reverts the fist commit I wrote. I must have used an outdated version of BehaviorTree.CPP.

**Comment by Affonso-Gui** [comment]
This fixed my build with BehaviorTree.CPP version 3.8! :+1:

**Comment by facontidavide** [comment]
I will change the version of the BT.CPP library in the git submodule and merge this. Thanks

**Comment by tonynajjar** [comment]
Having the same issue after the galactic sync, these changes fixes the build of Groot

**Comment by facontidavide** [comment]
Fixed https://github.com/BehaviorTree/Groot/commit/ee66489e6ea9ea3cbdd866d869aca8ea621035ce

**Comment by tharaka27** [comment]
```
catkin_ws/src/Groot/bt_editor/XML_utilities.cpp: In function \u2018bool VerifyXML(QDomDocument&, const std::vector<QString>&, std::vector<QString>&)\u2019:
/home/ros/catkin_ws/src/Groot/bt_editor/XML_utilities.cpp:203:33: error: invalid initialization of reference of type \u2018const std::set<std::__cxx11::basic_string<char> >&\u2019 from expression of type \u2018std::unordered_map<std::__cxx11::basic_string<char>, BT::NodeType>\u2019
  203 |         BT::VerifyXML(xml_text, registered_nodes); // may throw
      |                                 ^~~~~~~~~~~~~~~~
In file included from /home/ros/catkin_ws/src/Groot/bt_editor/XML_utilities.cpp:6:
/catkin_ws/src/BehaviorTree.CPP/include/behaviortree_cpp_v3/xml_parsing.h:38:45: note: in passing argument 2 of \void BT::VerifyXML(const string&, const std::set<std::__cxx11::basic_string<char> >&)\u2019
   38 |                const std::set<std::string> &registered_nodes);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/behavior_tree_editor.dir/build.make:251: CMakeFiles/behavior_tree_editor.dir/bt_editor/XML_utilities.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:247: CMakeFiles/behavior_tree_editor.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```
Error still persists even after using submodule.
Any suggestions please ?

**Comment by facontidavide** [comment]
Look at your log man!
```

**Comment by tharaka27** [comment]
Thanks a lot :) I didn't notice that I have another BehaviorTreeRepo

**Comment by tianyaohu** [comment]
Hey I tried to build with `cmake --build -build` as in README, the XML_utilities.cpp compilation error still exists


/home/user/ros2_ws/Groot/bt_editor/XML_utilities.cpp: In function 'bool VerifyXML(QDomDocument&, const std::vector<QString>&, std::vector<QString>&)':
/home/user/ros2_ws/Groot/bt_editor/XML_utilities.cpp:203:33: error: invalid initialization of reference of type 'const std::set<std::__cxx11::basic_string<char> >&' from expression of type 'std::unordered_map<std::__cxx11::basic_string<char>, BT::NodeType>'
  203 |         BT::VerifyXML(xml_text, registered_nodes); // may throw
      |                                 ^~~~~~~~~~~~~~~~
In file included from /home/user/ros2_ws/Groot/bt_editor/XML_utilities.cpp:6:
/opt/ros/noetic/include/behaviortree_cpp_v3/xml_parsing.h:38:45: note: in passing argument 2 of 'void BT::VerifyXML(const string&, const std::set<std::__cxx11::basic_string<char> >&)'
   38 |                const std::set<std::string> &registered_nodes);
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/behavior_tree_editor.dir/build.make:251: CMakeFiles/behavior_tree_editor.dir/bt_editor/XML_utilities.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:303: CMakeFiles/behavior_tree_editor.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Pull request closed without merging**
